name: Run Robot Test

on:
  workflow_dispatch:
    inputs:
      hum-token:
        description: "Humanitec Token"
        required: true
      hum-org:
        description: "Humanitec Org"
        required: true
      image-name:
        description: "Image Name"
        required: true

env:
  HUMANITEC_TOKEN: ${{ github.event.inputs.hum-token }}
  HUMANITEC_ORG: ${{ github.event.inputs.hum-org }}
  IMAGE_NAME: ${{ github.event.inputs.image-name }}

jobs:
  notify-humanitec:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export GITSHA=1234567 \
          export GITTAG=1.1.1 \
          export IMAGENAME=${{ env.IMAGE_NAME }} \
          export REGISTRY=ghcr.io/test \
          export BRANCH=main

      - name: Send Image Notification
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.humanitec.io/orgs/${{ env.HUMANITEC_ORG }}/images/'$IMAGENAME'/builds"
          method: "POST"
          bearerToken: ${{ env.HUMANITEC_TOKEN }}
          data: |
            {
              "branch": "'$BRANCH'",
              "commit": "'$GITSHA'",
              "image": "'$REGISTRY'/'$IMAGENAME':'$GITTAG'",
              "tags": ["'$GITTAG'"],
            }
