name: Run Robot Test

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: "workflow run identifier"
        required: false
      url:
        description: "Which URL to check"
        required: false
        default: "https://duckduckgo.com/"
      text:
        description: "Which text to check on the URL"
        required: false
        default: "DuckDuckGo"
env:
  RUN_ID: ${{ github.event.inputs.run-id }}
  URL: ${{ github.event.inputs.url }}
  TEXT: ${{ github.event.inputs.text }}

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This test run with ID: ${{ env.RUN_ID }} will check if the text ${{ env.TEXT }} is present on ${{ env.URL }}"

  robot_test:
    runs-on: ubuntu-latest
    name: ${{github.event.inputs.run-id}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_options: "-v URL:'${{ env.URL }}' -v TEXT:'${{ env.TEXT }}'"
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
